#!/bin/bash
#for i in ./locale/*.ts; do
    #sed -i -e 's|filename="../|filename="|g' -e 's|“|&#xe2;&#x80;&#x9c;|g' -e 's|”|&#xe2;&#x80;&#x9d;|g' -e 's|‘|&#xe2;&#x80;&#x98;|g' -e 's|’|&#xe2;&#x80;&#x99;|g' -e 's|…|&#xe2;&#x80;&#xa6;|g' -e 's|–|&#xe2;&#x80;&#x93;|g' -e 's|—|&#xe2;&#x80;&#x94;|g' $i
#done
pylupdate4 -verbose aurqt.pro
for i in ./locale/*.ts; do
    # pylupdate4 is dumb and mangles encodings
    sed -i -e 's|filename="|filename="../|g' -e 's|&#xe2;&#x80;&#x9c;|“|g' -e 's|&#xe2;&#x80;&#x9d;|”|g' -e 's|&#xe2;&#x80;&#x98;|‘|g' -e 's|&#xe2;&#x80;&#x99;|’|g' -e 's|&#xe2;&#x80;&#xa6;|…|g' -e 's|&#xe2;&#x80;&#x93;|–|g' -e 's|&#xe2;&#x80;&#x94;|—|g' $i
done
lrelease aurqt.pro
pyrcc4 -py3 aurqt.qrc -o aurqt/ui/resources.py

# vim: textwidth=500
